import {DEMO_PASSWORD,can,createAccountState,currentAccount,roleOf,assertPermission,loginDemo,logoutDemo,registerMember,verifyDemo,updateProfile,ownBookings,attachBookingCustomer,requestBookingChange,resolveRequest,saveCustomerNote,saveStaff} from './accounts-model.js?v=20260926-members1';
export function createAccounts({getState,render,navigate,modal,header,dialog,toast,esc,money,fmt,badge,showBooking}){
 let data=createAccountState(getState().bookings),loginKind='member',crmQuery='';
 const L=(th,en)=>`<span translate="no" data-roomcopy-th="${esc(th)}" data-roomcopy-en="${esc(en)}">${esc(th)}</span>`;
 const current=()=>currentAccount(data),role=()=>roleOf(data),has=p=>can(role(),p);
 const sync=()=>{getState().role=role();getState().actor=current()?.name||'Guest Demo';};sync();
 const demoNote=()=>`<div class="account-demo-note">${L('ทดลองด้วยข้อมูลสมมติเท่านั้น · ไม่มีการส่งอีเมลจริง · ข้อมูลหายเมื่อรีเฟรช','Use sample data only · No real emails · Refresh resets all data')}</div>`;
 const title=(th,en,subTh,subEn)=>`<div class="page-title"><div><div class="eyebrow">SUNTARA GRAND</div><h1>${L(th,en)}</h1><p>${L(subTh,subEn)}</p></div><span class="sample-tag">DEMO</span></div>`;
 function nav(){const u=current();return `<button class="account-nav-button" data-action="acct-member">${L(u&&role()==='member'?'บัญชีของฉัน':'สมาชิก',u&&role()==='member'?'My account':'Member')}</button>${u?`<span class="account-session" translate="no">${esc(u.name)} · ${role()}</span><button class="text-button" data-action="acct-logout">${L('ออกจากระบบ','Sign out')}</button>`:''}`;}
 function loginPage(kind=loginKind){loginKind=kind;const staff=kind==='staff',list=staff?data.staff.filter(u=>u.active):data.customers.filter(u=>u.member&&u.verified);return `<section class="account-page"><div class="auth-layout"><div class="auth-intro"><div class="eyebrow">${staff?'STAFF WORKSPACE':'SUNTARA GRAND MEMBERS'}</div><h1>${staff?L('ทุกหน้าที่ มีพื้นที่ของตัวเอง','A workspace for every role'):L('การพักครั้งต่อไป เริ่มได้ง่ายขึ้น','Your next stay, made easier')}</h1><p>${staff?L('เข้าสู่ระบบเพื่อจัดการห้องพัก การจอง และข้อมูลลูกค้าตามสิทธิ์ของคุณ','Sign in to manage rooms, reservations and customers with your assigned permissions'):L('เก็บข้อมูลผู้จอง ดูประวัติ และติดตามคำขอได้ในที่เดียว','Keep your details, view reservations and follow requests in one place')}</p><div class="auth-benefits">${(staff?[["Admin","จัดการบัญชีและตั้งค่าห้อง","Accounts and room setup"],["Manager","ราคา โปรโมชั่น และรายงาน","Rates, offers and reports"],["Front","ห้องเปิดขายและรายการจอง","Room availability and bookings"]]:[["01","ดูการจองของตนเอง","Your own reservations"],["02","จองครั้งถัดไปได้เร็วขึ้น","Faster booking next time"],["03","เลือกการรับข่าวสารได้","Control your email preferences"]]).map(([n,t,e])=>`<div><strong>${n}</strong><span>${L(t,e)}</span></div>`).join('')}</div><button class="text-button" data-action="guest">${L('กลับไปดูห้องพัก · จองได้โดยไม่สมัครสมาชิก','Browse rooms · Guest booking is available')}</button></div><div class="auth-card"><h2>${staff?L('เข้าสู่ระบบพนักงาน','Staff sign in'):L('เข้าสู่ระบบสมาชิก','Member sign in')}</h2><p>${L('เลือกบัญชีเพื่อเติมข้อมูลทดลอง','Choose an account to fill the demo credentials')}</p><div class="demo-accounts">${list.map(u=>`<button type="button" class="secondary" data-action="acct-fill" data-id="${esc(u.email)}">${esc(staff?u.role:u.name)}</button>`).join('')}</div><form id="acct-login-form" data-kind="${kind}"><label>${L('อีเมล','Email')}<input id="account-email" name="email" type="email" value="${staff?'front@example.com':'member@example.com'}" required autocomplete="off"></label><label>${L('รหัสผ่านตัวอย่าง','Demo password')}<input name="password" type="password" value="${DEMO_PASSWORD}" required autocomplete="off"></label><p class="tiny">${L('รหัสทดลองทุกบัญชี','Password for all demo accounts')}: <code translate="no">${DEMO_PASSWORD}</code></p><div class="account-error" role="alert"></div><button class="primary auth-submit">${L('เข้าสู่ระบบตัวอย่าง','Sign in to demo')}</button></form><button class="text-button" data-action="acct-forgot">${L('ลืมรหัสผ่าน','Forgot password')}</button>${staff?'':`<div class="auth-register">${L('ยังไม่มีบัญชีสมาชิก?','New to Suntara Grand?')} <button class="text-button" data-action="acct-register">${L('สมัครสมาชิก','Create an account')}</button></div>`}${demoNote()}</div></div></section>`;}
 function consentField(value){return `<label class="check-label"><input name="consent" type="checkbox" ${value?'checked':''}><span>${L('รับข่าวสารและโปรโมชั่นทางอีเมล (ไม่บังคับ และยกเลิกได้)','Receive news and offers by email (optional; withdraw any time)')}</span></label>`;}
 function contactFields(c={},register=false){return `<div class="form-grid"><label>${L('ชื่อผู้จอง','Full name')}<input name="name" maxlength="80" value="${esc(c.name||'Member Demo C')}" required autocomplete="off"></label><label>${L('เบอร์โทรศัพท์','Phone')}<input name="phone" inputmode="tel" pattern="0[0-9]{8,9}" value="${esc(c.phone||'0800000002')}" required autocomplete="off"></label><label>${L('อีเมล','Email')}<input name="email" type="email" value="${esc(c.email||'newmember@example.com')}" ${register?'required':'readonly'} autocomplete="off"></label><label>${L('ภาษาที่ต้องการ','Preferred language')}<select name="language"><option value="th" ${c.language!=='en'?'selected':''}>ไทย / TH</option><option value="en" ${c.language==='en'?'selected':''}>English / EN</option></select></label>${register?`<label class="full">${L('รหัสผ่านตัวอย่าง','Demo password')}<input name="password" value="${DEMO_PASSWORD}" readonly><span class="tiny">${L('ไม่ต้องกรอกรหัสผ่านจริงใน Demo','Do not enter a real password in this demo')}</span></label>`:''}</div>`;}
 function registerDialog(){modal(header(L('สมัครสมาชิก','Create an account'))+`<form class="modal-body" id="acct-register-form">${demoNote()}${contactFields({},true)}${consentField(false)}<p class="tiny">${L('ข้อมูลใช้สำหรับบัญชีและการจอง ส่วนการรับโปรโมชั่นเป็นตัวเลือกแยกต่างหาก','Account and booking details are separate from optional marketing preferences')}</p><label class="check-label"><input type="checkbox" required><span>${L('รับทราบว่าเป็น Demo และจะใช้ข้อมูลสมมติเท่านั้น','I understand this is a demo and will use sample data only')}</span></label><div class="form-error" role="alert"></div><div class="modal-actions"><button type="button" class="secondary" data-action="close">${L('ยกเลิก','Cancel')}</button><button class="primary">${L('สร้างบัญชีทดลอง','Create demo account')}</button></div></form>`);}
 function requestList(list,staff=false){return list.map(r=>`<article class="member-request"><div><strong>${r.bookingId}</strong> <span class="badge ${r.status==='pending'?'pending':'open'}">${r.status==='pending'?L('รอดำเนินการ','Awaiting staff'):L('ตอบกลับแล้ว','Replied')}</span><p>${r.kind==='cancel'?L('ขอยกเลิก','Cancellation request'):L('ขอเปลี่ยนแปลง','Change request')}</p><p translate="no">${esc(r.message)}</p>${r.reply?`<p class="reply" translate="no">${esc(r.reply)}</p>`:''}</div>${staff&&r.status==='pending'?`<div class="request-actions"><button class="secondary" data-action="booking" data-id="${r.bookingId}">${L('จัดการรายการจอง','Manage reservation')}</button><button class="primary" data-action="acct-resolve" data-id="${r.id}">${L('บันทึกผลตอบกลับ','Record reply')}</button></div>`:''}</article>`).join('')||`<p class="empty">${L('ยังไม่มีคำขอ','No requests yet')}</p>`;}
 function memberPage(){const c=current();if(role()!=='member')return loginPage('member');const bookings=ownBookings(data,getState().bookings);return `<section class="container account-page">${title('บัญชีของฉัน','My account','ข้อมูลและการจองของคุณในที่เดียว','Your profile and reservations in one place')}${demoNote()}<div class="member-layout"><section class="panel profile-panel"><div class="panel-head"><h2>${L('ข้อมูลสมาชิก','Member profile')}</h2><span class="badge open">${L('ยืนยันอีเมลแล้ว','Email verified')}</span></div><form id="acct-profile-form">${contactFields(c)}${consentField(c.consent)}<p class="tiny">${L('การแก้ชื่อไม่เปลี่ยนข้อมูลผู้จองในรายการเดิม','Changing your name does not rewrite existing reservations')}</p><div class="account-error" role="alert"></div><button class="primary">${L('บันทึกข้อมูลสมาชิก','Save profile')}</button></form></section><section class="panel member-bookings"><div class="panel-head"><div><h2>${L('การจองของฉัน','My reservations')}</h2><p>${L('แสดงเฉพาะรายการที่เชื่อมกับบัญชีนี้','Only reservations linked to this account')}</p></div><button class="secondary" data-action="guest">${L('จองห้องพัก','Book a room')}</button></div>${bookings.map(b=>`<article class="member-booking"><div><span class="eyebrow">${b.id}</span><h3>${getState().types.find(t=>t.id===b.type)?.name}</h3><p>${fmt(b.start)} — ${fmt(b.end)}</p>${badge(b.status)}</div><div><strong>฿${money(b.total)}</strong><p>${L('ชำระที่โรงแรม','Pay at the hotel')}</p>${b.status!=='cancelled'?`<button class="text-button" data-action="acct-request" data-id="${b.id}">${L('ขอเปลี่ยนแปลง / ยกเลิก','Request change / cancellation')}</button>`:''}</div></article>`).join('')||`<div class="empty">${L('ยังไม่มีการจอง ลองเลือกห้องพักเพื่อเริ่มต้น','No reservations yet. Choose a room to get started')}</div>`}<h3 class="request-heading">${L('ติดตามคำขอของฉัน','My requests')}</h3>${requestList(data.requests.filter(r=>r.customerId===c.id))}</section></div></section>`;}
 function crmPage(){assertPermission(data,'customers');const list=data.customers.filter(c=>(c.name+' '+c.email+' '+c.phone).toLowerCase().includes(crmQuery.toLowerCase()));return `${title('ข้อมูลลูกค้า','Customer records','ประวัติการจองและบันทึกการบริการ','Reservation history and service notes')}${demoNote()}<div class="crm-metrics"><div><span>${L('ลูกค้าทั้งหมด','Customer records')}</span><strong>${data.customers.length}</strong></div><div><span>${L('บัญชีสมาชิก','Member accounts')}</span><strong>${data.customers.filter(c=>c.member).length}</strong></div><div><span>${L('คำขอรอดำเนินการ','Pending requests')}</span><strong>${data.requests.filter(r=>r.status==='pending').length}</strong></div></div><section class="panel"><div class="panel-head"><h2>${L('ทะเบียนลูกค้า','Customer directory')}</h2><form id="acct-customer-search" class="customer-search"><label class="sr-only" for="customer-query">${L('ค้นหาลูกค้า','Search customers')}</label><input id="customer-query" name="query" value="${esc(crmQuery)}" placeholder="Name / email / phone"><button class="secondary">${L('ค้นหา','Search')}</button></form></div><div class="table-scroll"><table><thead><tr><th>${L('ลูกค้า','Customer')}</th><th>${L('ประเภทบัญชี','Account')}</th><th>${L('รายการจอง','Reservations')}</th><th>${L('การรับข่าวสาร','Marketing')}</th><th></th></tr></thead><tbody>${list.map(c=>`<tr><td><strong translate="no">${esc(c.name)}</strong><div class="table-sub" translate="no">${esc(c.email)}</div></td><td>${c.member?L('สมาชิก','Member'):L('ไม่สมัครสมาชิก','Guest')}</td><td>${getState().bookings.filter(b=>b.customerId===c.id).length}</td><td>${c.consent?L('ยินยอม','Opted in'):L('ไม่รับข่าวสาร','Not subscribed')}</td><td><button class="table-action" data-action="acct-customer" data-id="${c.id}">${L('ดูประวัติ','View record')}</button></td></tr>`).join('')||`<tr><td colspan="5">${L('ไม่พบลูกค้า','No matching customers')}</td></tr>`}</tbody></table></div></section><section class="panel customer-requests"><div class="panel-head"><h2>${L('คำขอจากสมาชิก','Member requests')}</h2></div>${requestList(data.requests,true)}</section><p class="front-foot">${L('ข้อมูลจากเว็บไซต์นี้เท่านั้น · ประวัติเก่าจาก Easyfo ยังไม่เชื่อมอัตโนมัติ · ยังไม่มีคะแนนสะสมหรือส่งแคมเปญ','Website records only · No automatic Easyfo history sync · No loyalty points or campaign sending')}</p>`;}
 function customerDialog(id){assertPermission(data,'customers');const c=data.customers.find(c=>c.id===id);if(!c)return;const bs=getState().bookings.filter(b=>b.customerId===id);modal(header(L('ประวัติลูกค้า','Customer record'),esc(c.name))+`<div class="modal-body">${demoNote()}<div class="info-list"><div class="info-item"><span>Email</span><strong translate="no">${esc(c.email)}</strong></div><div class="info-item"><span>${L('โทรศัพท์','Phone')}</span><strong>${esc(c.phone)}</strong></div><div class="info-item"><span>${L('รับข่าวสาร','Marketing')}</span><strong>${c.consent?L('ยินยอม','Opted in'):L('ไม่รับข่าวสาร','Not subscribed')}</strong></div></div><h3>${L('ประวัติการจองผ่านเว็บ','Website reservation history')}</h3>${bs.map(b=>`<div class="customer-history"><button class="text-button" data-action="booking" data-id="${b.id}">${b.id}</button>${badge(b.status)}<span>${fmt(b.start)}</span></div>`).join('')||`<p>${L('ยังไม่มีการจอง','No reservations yet')}</p>`}<form id="acct-note-form" data-id="${id}"><label>${L('บันทึกการบริการ','Service notes')}<textarea name="notes" rows="3" maxlength="500">${esc(c.notes)}</textarea></label><p class="tiny">${L('บันทึกเฉพาะข้อมูลจำเป็นต่อบริการ ไม่บันทึกรหัสผ่านหรือข้อมูลอ่อนไหว','Keep only necessary service notes. Do not enter passwords or sensitive information')}</p><div class="form-error" role="alert"></div><button class="primary">${L('บันทึกโน้ต','Save note')}</button></form></div>`);}
 const matrix=[['inventory','เปิด–ปิดขาย / จัดการจอง','Availability / bookings'],['customers','ทะเบียนลูกค้า / บันทึกบริการ','Customer records / notes'],['settings','ราคาและข้อมูลห้อง','Rates and room content'],['analytics','รายงานและประวัติแก้ไข','Reports and audit trail'],['rooms','เพิ่ม / แก้ข้อมูลหลักของห้อง','Room catalog changes'],['users','บัญชีพนักงานและสิทธิ์','Staff accounts and roles']];
 function usersPage(){assertPermission(data,'users');return `${title('บัญชีพนักงานและสิทธิ์','Staff accounts and roles','แต่ละคนใช้บัญชีของตนเองและทำงานตามหน้าที่','Individual accounts with permissions for each role')}${demoNote()}<section class="panel"><div class="panel-head"><h2>${L('พนักงาน','Staff')}</h2><button class="primary" data-action="acct-staff-edit">${L('เพิ่มพนักงาน','Add staff')}</button></div><div class="table-scroll"><table><thead><tr><th>${L('ชื่อ / อีเมล','Name / email')}</th><th>Role</th><th>${L('สถานะ','Status')}</th><th></th></tr></thead><tbody>${data.staff.map(u=>`<tr><td><strong translate="no">${esc(u.name)}</strong><div class="table-sub" translate="no">${esc(u.email)}</div></td><td>${u.role}</td><td><span class="badge ${u.active?'open':'closed'}">${u.active?L('ใช้งาน','Active'):L('ปิดบัญชี','Disabled')}</span></td><td><button class="table-action" data-action="acct-staff-edit" data-id="${u.id}">${L('แก้ไข','Edit')}</button></td></tr>`).join('')}</tbody></table></div></section><section class="panel permission-panel"><div class="panel-head"><h2>${L('ตารางสิทธิ์เริ่มต้น','Default permissions')}</h2></div><div class="table-scroll"><table><thead><tr><th>${L('เมนู / การทำงาน','Menu / action')}</th><th>Front</th><th>Manager</th><th>Admin</th></tr></thead><tbody>${matrix.map(([p,t,e])=>`<tr><td>${L(t,e)}</td>${['front','manager','admin'].map(r=>`<td>${can(r,p)?L('ใช้งานได้','Allowed'):'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
 function staffDialog(id){assertPermission(data,'users');const u=data.staff.find(x=>x.id===id)||{name:'Staff Demo',email:'staff@example.com',role:'front',active:true};modal(header(L('จัดการบัญชีพนักงาน','Manage staff account'))+`<form id="acct-staff-form" data-id="${id||''}" class="modal-body"><div class="form-grid"><label>${L('ชื่อพนักงาน','Staff name')}<input name="name" value="${esc(u.name)}" maxlength="80" required></label><label>Email<input name="email" type="email" value="${esc(u.email)}" required></label><label>Role<select name="role">${['front','manager','admin'].map(r=>`<option value="${r}" ${r===u.role?'selected':''}>${r}</option>`).join('')}</select></label></div><label class="check-label"><input name="active" type="checkbox" ${u.active?'checked':''}>${L('เปิดใช้งานบัญชี','Account enabled')}</label><p class="tiny">${L('ตัวอย่างใช้รหัส Demo1234! · ระบบจริงต้องเชิญพนักงานตั้งรหัสของตนเอง','Demo password: Demo1234! · In production, staff set their own passwords')}</p><div class="form-error" role="alert"></div><button class="primary">${L('บันทึกบัญชี','Save account')}</button></form>`);}
 function requestDialog(id){const b=ownBookings(data,getState().bookings).find(x=>x.id===id);if(!b)throw Error('บัญชีนี้ไม่มีสิทธิ์ทำรายการ');modal(header(L('ส่งคำขอถึง Front','Send a request to Front'),id)+`<form id="acct-request-form" data-id="${id}" class="modal-body"><div class="notice">${L('คำขอจะยังไม่เปลี่ยนวัน ราคา หรือยกเลิกห้อง จนกว่าพนักงานจะดำเนินการ','A request does not change dates, prices or cancel the room until staff act on it')}</div><label>${L('ประเภทคำขอ','Request type')}<select name="kind"><option value="change">${L('ขอเปลี่ยนแปลง','Change request')}</option><option value="cancel">${L('ขอยกเลิก','Cancellation request')}</option></select></label><label>${L('รายละเอียด','Details')}<textarea name="message" rows="3" maxlength="500" required></textarea></label><div class="form-error" role="alert"></div><button class="primary">${L('ส่งคำขอ','Send request')}</button></form>`);}
 function handleAction(action,id){if(!action.startsWith('acct-'))return false;switch(action){
 case 'acct-member':dialog.close();navigate('member');break;
 case 'acct-logout':logoutDemo(data);sync();dialog.close();navigate('guest');break;
 case 'acct-fill':{const input=document.querySelector('#account-email');if(input)input.value=id;break;}
 case 'acct-register':registerDialog();break;
 case 'acct-verify':verifyDemo(data,id);modal(header(L('ยืนยันอีเมลตัวอย่างแล้ว','Demo email verified'))+`<div class="modal-body"><p>${L('ไม่มีอีเมลถูกส่งจริง สามารถเข้าสู่ระบบด้วยบัญชีที่เพิ่งสร้างและรหัส Demo1234!','No email was sent. Sign in with your new demo account and Demo1234!')}</p><button class="primary" data-action="acct-member">${L('ไปเข้าสู่ระบบ','Go to sign in')}</button></div>`);break;
 case 'acct-forgot':modal(header(L('กู้คืนบัญชี','Account recovery'))+`<form id="acct-forgot-form" class="modal-body"><label>Email<input name="email" type="email" value="member@example.com" required></label><p>${L('ระบบจริงจะส่งลิงก์ที่มีอายุจำกัด ตัวอย่างนี้ไม่ส่งอีเมล','Production uses a time-limited link. This demo sends no email')}</p><button class="primary">${L('ทดลองขอลิงก์','Simulate recovery request')}</button></form>`);break;
 case 'acct-customer':customerDialog(id);break;case 'acct-staff-edit':staffDialog(id);break;case 'acct-request':requestDialog(id);break;
 case 'acct-resolve':assertPermission(data,'bookings');modal(header(L('บันทึกผลคำขอ','Record request outcome'))+`<form id="acct-resolve-form" data-id="${id}" class="modal-body"><p>${L('ดำเนินการในรายการจองและ Easyfo ให้เรียบร้อยก่อนตอบกลับ การตอบนี้ไม่เปลี่ยนสถานะห้องเอง','Update the reservation and Easyfo before replying. A reply does not change room status')}</p><label>${L('ผลดำเนินการ / คำตอบ','Outcome / reply')}<textarea name="reply" rows="3" maxlength="500" required></textarea></label><div class="form-error" role="alert"></div><button class="primary">${L('บันทึกผลตอบกลับ','Record reply')}</button></form>`);break;
 }return true;}
 function handleSubmit(form,v){if(!form.id.startsWith('acct-'))return false;switch(form.id){
 case 'acct-login-form':loginDemo(data,form.dataset.kind,v.email,v.password);sync();navigate(form.dataset.kind==='staff'?'front':'member');break;
 case 'acct-register-form':{const c=registerMember(data,{...v,consent:v.consent==='on'});modal(header(L('จำลองการยืนยันอีเมล','Simulate email verification'))+`<div class="modal-body"><p translate="no">${esc(c.email)}</p><p>${L('ตัวอย่างยังไม่ส่งอีเมล กดปุ่มเพื่อจำลองการเปิดลิงก์ยืนยัน','No email is sent. Use this button to simulate opening a verification link')}</p><button class="primary" data-action="acct-verify" data-id="${c.id}">${L('จำลองยืนยันอีเมล','Simulate verification')}</button></div>`);break;}
 case 'acct-profile-form':updateProfile(data,{...v,consent:v.consent==='on'});render();toast('บันทึกข้อมูลสมาชิกตัวอย่างแล้ว');break;
 case 'acct-forgot-form':modal(header(L('รับคำขอตัวอย่างแล้ว','Demo request received'))+`<div class="modal-body"><p>${L('ในระบบจริง หากบัญชีตรงกับข้อมูล ระบบจะส่งวิธีกู้คืนไปยังอีเมล ตัวอย่างนี้ไม่มีการส่งหรือเปลี่ยนรหัสผ่าน','In production, a matching account receives recovery instructions. This demo sends nothing and changes no password')}</p><button class="primary" data-action="close">${L('ปิดหน้าต่าง','Close')}</button></div>`);break;
 case 'acct-customer-search':crmQuery=v.query.trim();render();break;
 case 'acct-note-form':saveCustomerNote(data,form.dataset.id,v.notes);dialog.close();render();toast('บันทึกโน้ตตัวอย่างแล้ว');break;
 case 'acct-staff-form':saveStaff(data,form.dataset.id,{...v,active:v.active==='on'});sync();dialog.close();render();toast('บันทึกบัญชีพนักงานตัวอย่างแล้ว');break;
 case 'acct-request-form':requestBookingChange(data,getState().bookings,form.dataset.id,v.kind,v.message);dialog.close();render();toast('ส่งคำขอตัวอย่างถึง Front แล้ว');break;
 case 'acct-resolve-form':resolveRequest(data,form.dataset.id,v.reply);dialog.close();render();toast('บันทึกผลตอบกลับตัวอย่างแล้ว');break;
 }return true;}
 function guardAction(action,id){const admin=['edit-room','add-room','manage-rooms','room-catalog','room-life','import-rooms','apply-import','layout-move','layout-reset','layout-save','master-floor','master-mode'];const bookings=['booking','confirm','cancel-prompt','cancel','move-booking'];const inventory=['room','bulk','single-availability'];if(admin.includes(action))assertPermission(data,'rooms');if(bookings.includes(action))assertPermission(data,'bookings');if(inventory.includes(action))assertPermission(data,'inventory');if(action==='edit')assertPermission(data,'settings');if(action==='section'&&!has(id==='master'?'inventory':id))throw Error('บัญชีนี้ไม่มีสิทธิ์ทำรายการ');if(action==='feature-report')assertPermission(data,'analytics');}
 function guardForm(id){const map={'range-form':'inventory','room-search':'inventory','availability-form':'inventory','move-booking-form':'bookings','easyfo-form':'bookings','edit-room-form':'rooms','room-life-form':'rooms','import-preview-form':'rooms','edit-form':'settings'};if(map[id])assertPermission(data,map[id]);}
 function requestsBanner(){const n=data.requests.filter(r=>r.status==='pending').length;return n?`<div class="notice amber"><span>${L('คำขอจากสมาชิกที่รอดำเนินการ','Pending member requests')}: <strong>${n}</strong></span><button class="text-button" data-action="section" data-id="customers">${L('ดูคำขอ','View requests')}</button></div>`:'';}
 return {nav,loginPage,memberPage,crmPage,usersPage,handleAction,handleSubmit,guardAction,guardForm,current,role,has,sync,requestsBanner,events:()=>data.events,reset(){data=createAccountState(getState().bookings);sync();crmQuery='';},attach:(r,v)=>attachBookingCustomer(data,r,v),loginForTest(kind,email){loginDemo(data,kind,email,DEMO_PASSWORD);sync();},getData:()=>data};
}
